version: "3.7"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - .docker.mysql.env
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  php-fpm:
    build: docker/php
    restart: on-failure
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/api

# volumes
volumes:
  dbdata:
    driver: local
