version: "3.7"

services:
  mysql:
    image: mysql:5.7
    env_file:
      - .docker.mysql.env
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  webserver:
    build: docker/nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/api
      - ./var/logs/nginx/:/var/log/nginx:cached
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - mysql
      - php-fpm

  php-fpm:
    build: docker/php
    restart: on-failure
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/api

# volumes
volumes:
  dbdata:
    driver: local
